/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zime_media_ZIMEVideoClientJNI_StrPtr */

#ifndef _Included_zime_media_ZIMEVideoClientJNI_StrPtr
#define _Included_zime_media_ZIMEVideoClientJNI_StrPtr
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
