/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zime_media_ZIMEVideoClientJNI_ZIMEAudioCodeInfo */

#ifndef _Included_zime_media_ZIMEVideoClientJNI_ZIMEAudioCodeInfo
#define _Included_zime_media_ZIMEVideoClientJNI_ZIMEAudioCodeInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
